- sdl2/test/sdlmixer_test.py
- sdl2/test/version_test.py
Similarly to sdlimage_test, allow newer patch-version of other SDL2
libraries. There is no technical reason to prevent people from upgrading
libsdl2 while having old PySDL2 installed, and there is no reason to
make tests fail every time libsdl2 happens to be upgraded.
Closes: https://github.com/marcusva/py-sdl2/issues/115
> test: Always allow greater patch-version of SDL2

- sdl2/test/audio_test.py
- sdl2/test/blendmode_test.py
- sdl2/test/gamecontroller_test.py
- sdl2/test/joystick_test.py
- sdl2/test/keyboard_test.py
- sdl2/test/render_test.py
- sdl2/test/sdl2ext_draw_test.py
- sdl2/test/sdl2ext_font_test.py
- sdl2/test/sdl2ext_gui_test.py
- sdl2/test/sdl2ext_image_test.py
- sdl2/test/sdl2ext_pixelaccess_test.py
- sdl2/test/sdl2ext_sprite_test.py
- sdl2/test/sdl2ext_test.py
- sdl2/test/sdl2ext_window_test.py
- sdl2/test/sdl_test.py
- sdl2/test/sdlgfx_test.py
- sdl2/test/shape_test.py
- sdl2/test/syswm_test.py
- sdl2/test/timer_test.py
- sdl2/test/video_test.py
- sdl2/test/vulkan_test.py
All of the SDL2 subsystems are optional. Add an appropriate logic to
skip tests if SDL2 is built without them.
While missing audio and video subsystems are rather unlikely,
e.g. the haptic subsystem is rarely actually necessary (especially with
no compatible hardware). However, supporting every (or least most of)
missing subsystems should be cleaner and not cause any harm.
While technically SDL2_Init() and related functions can fail with other
errors, it is rather unlikely that the tests would be able to trigger
any real problem with the code that would result in non-zero return
value of this function.
Closes: https://github.com/marcusva/py-sdl2/issues/116
> test: Skip tests on missing subsystems gracefully

- sdl2/ext/window.py
Eliminates an exception when a Window is destroyed but the call to
SDL_CreateWindow has not yet happened.
> Check for window attribute on Window object close

- sdl2/dll.py
- sdl2/sdlmixer.py
The pre-built SDL2 binaries for macOS on the official website are all packaged in .framework format. However, PySDL2 currently only looks for SDL2 DLLs in .dylib format, meaning that if you download the official frameworks and try to point `PYSDL2_DLL_PATH` towards them, it won't be able to find them.
This patch fixes this, and lays the groundwork for having a separate 'pysdl2-dlls wheel' that contains the official pre-built SDL2 + extras runtime libraries which would solve #78 (I currently have a script/package to create such a wheel for macOS and it seems to work well using this fix!)
> Allow .framework DLLs on macOS

- sdl2/dll.py
The code on line 14
```python
if platform in ("win32",):
```
has redundant `in` expression. Change it into `==` might be better.
> removed redundant 'in' expr

- doc/modules/sdl2ext_common.rst
- doc/tutorial/pygamers.rst
- Looked at the `sdl2.ext.init()` function and compared it with `pygame.init()` in the Pygame sources
- Added comparison between `sdl2.ext.init()` and `SDL_Init()` to Initialization Routines page
- Added comparison between `sdl2.ext.init()` and `pygame.init()` to the Pygamers page
- Built the docs locally and made sure no links are broken
> Fixes #33: Document differences between init functions

- sdl2/ext/font.py
Fixed AttributeError: 'LP_SDL_Surface' object has no attribute 'w' in Python 3.6
Added respecting bg_color when using TTF_RenderUTF8_Blended_Wrapped
> fix(ext.fronts): Fixed usage of TTF_RenderUTF8_Blended_Wrapped with background

- appveyor.yml
- sdl2/gamecontroller.py
- sdl2/joystick.py
- sdl2/test/gamecontroller_test.py
- sdl2/test/joystick_test.py
Should fix #75. Based on @Kentzo's fix for SDL_JoystickGetGUIDString, but implements the same interface as the actual SDL function, and also fixes SDL_GameControllerMappingForGUID which also caused a segfault for the same reason. The ctypes bug responsible for the segfault is fixed as of Python 3.8.0, so on 3.8+ the real SDL2 functions are used instead of the reimplementations.
Also, in the process I wrote a bunch of new unit tests for the gamepad module, so those are in here too.
> Fix Python segfault with Joystick/Gamepad GUID functions

- README.md
The link wan't working as it included the full stop.
> Move full stop out of readme link

- sdl2/ext/image.py
Calling load_image using a PNG file with indexed colors discarded the transparent palette index value, so all transparent pixels turned into whatever solid color is internally stored in the file that isn't typically seen. This change takes note of the transparency index and sets this as the color key on the resulting SDL surface, so that blitting operations will treat it as transparent.
The `isinstance` check exists because `info['transparency']` may not be an int: if the file is a PNG file with a per-palette alpha value it will be a bytearray, which is not supported here. See https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html for details on this.
Here's a demo indexed PNG file with palette index zero transparent:
PIL will report that index zero has RGB value (115, …
> Set color key for indexed images

- sdl2/dll.py
Addresses #78, at least for Windows and macOS (Linux support possible, but complicated, with future pysdl2-dll updates).
To summarize my posts in #78: [pysdl2-dll](https://github.com/a-hurst/pysdl2-dll) is a separate package that's essentially just the official SDL2+ttf+mixer+image and unofficial SDL2_gfx binaries for the platform plus an `__init__.py` file that, if `PYSDL2_DLL_PATH` isn't already set, sets it to the path with the DLLs in the package. I've been using this for deploying pysdl2 scripts to virtualenvs on Windows machines for a few months now and it's made installation/usage extremely smooth.
All this pull request does is make pysdl2 try to load pysdl2-dll automatically on launch, so all someone needs to do is run `pip install pysdl2 pysdl2dll` and they'll be able to run any …
> Add built-in support for the pysdl2-dll package

- sdl2/dll.py
The SDL2 library is named libSDL2-2.0.0.dylib by default on MacOS when installed with brew.
Right now, detecting the library on MacOS works because when installing through brew, there is a symlink that is created with the name libSDL2.dylib that links directly to the library itself.
The problem I have is that when building a python wheel on MacOS, I need to include the dependencies to it. The tool that I use (delocate-wheel) copies the library but not the symlink, and pysdl2 is not able to detect the library. 
Since the name SDL2-2.0 was already enabled, I figured it would not be that big a stretch to also add SDL2-2.0.0 as a potential name.
> Allowing to detect the SDL2 library on MacOS with its original name.

- sdl2/dll.py
The output names of the SDL library, when built with CMake in debug mode, contain a 'd' suffix.
Adding the possibility to detect those libraries with pysdl2.
> Allowing to search for an SDL library that was built in a debug configuration.

- sdl2/ext/font.py
Adds a missing `.contents` to get an `SDL_Surface` from an `LP_SDL_Surface` when doing `BitmapFont.render`. Fixes #180
> Fix BitmapFont.render

- sdl2/dll.py
Due to restrictions placed on Microsoft Store apps, Python installed from the Microsoft Store isn't always able to load the SDL2 extension libraries correctly. Specifically, MS Store Python prevents dynamic linking to DLLs that aren't part of the system path or within the app's dependency tree, which prevents the dynamic dependencies for SDL2\_image/mixer/ttf (e.g. libFLAC, libpng) from being loaded, breaking support for multiple sound and image formats.
As a workaround, MS Store Python will allow loading of any libraries already attached to the process, so we can preload the problem DLLs with ctypes when importing image/mixer/ttf to fix things.
> Fix DLL loading with Python from the Microsoft Store 

- doc/news.rst
- sdl2/dll.py
- sdl2/ext/compat.py
- sdl2/ext/gui.py
- sdl2/ext/window.py
- sdl2/test/sdl2ext_gui_test.py
Closes #170. Adds a friendly Pythonic API for working with SDL2's MessageBox functions/structs, wrapping a lot of ctypes unpleasantness.
Also adds/tweaks a few utility functions to facilitate the new API which should also be useful elsewhere in `sdl2.ext`.
[news-file]: https://github.com/marcusva/py-sdl2/blob/master/doc/news.rst
> Add sdl2.ext wrapper for MessageBox API

- sdl2/test/sdl2ext_draw_test.py
- sdl2/test/sdl2ext_font_test.py
`sdl2ext_pixelaccess_test` skips tests which require NumPy if NumPy is not installed. Let's do it for the other tests requiring NumPy as well.
[news-file]: https://github.com/marcusva/py-sdl2/blob/master/doc/news.rst
> Skip tests when numpy is not available

- appveyor.yml
- doc/news.rst
- sdl2/dll.py
- sdl2/sdlgfx.py
- sdl2/sdlimage.py
- sdl2/sdlmixer.py
- sdl2/sdlttf.py
- sdl2/test/sdlgfx_test.py
- sdl2/test/sdlimage_test.py
- sdl2/test/sdlttf_test.py
This PR updates the Python bindings for the SDL2 add-on modules (TTF, Mixer, Image, and GFX) to use standard Python function definitions, allowing for keyword arguments, Sphinx autodoc support, better flexibility in terms of error handling, and more.
This PR also includes updates to the unit tests to more thoroughly test the add-on libraries to make sure this PR doesn't break anything.
[news-file]: …
> Improved bindings for TTF, Image, Mixer, and GFX

- doc/modules/ext/image.rst
- doc/news.rst
- sdl2/ext/image.py
- sdl2/test/sdl2ext_image_test.py
- sdl2/test/sdl2ext_sprite_test.py
This PR deprecates the `sdl2.ext.load_image` function (which returned inconsistent SDL surface types depending on the back end used), and adds the new functions `sdl2.ext.load_bmp` and `sdl2.ext.load_img` to take its place.
This also adds a new function `sdl2.ext.save_bmp` for saving SDL surfaces as BMP files, as well as another function `sdl2.ext.pillow_to_surface` for converting PIL `Image.Image()` objects into SDL surfaces.
[what-is-api]: …
> Rewrite and redocument the sdl2.ext.image API

- doc/modules/ext/bitmapfont.rst
- doc/news.rst
- sdl2/ext/bitmapfont.py
- sdl2/test/sdl2ext_font_test.py
This PR rewrites and re-documents the `sdl.ext.BitmapFont` class, fixing a wide range of bugs and API unpleasantness. The main new additions are the `render_text` method, which renders text to an SDL surface (converted to ARGB8888 format by default) and supports custom line heights, and a :meth:`remap` method for customizing the surface-to-character mappings and fine-tuning character sizes (e.g. making the "i" character narrower than the "o" character).
Additionally, this PR deprecates the  `render` method as it returns a `SoftwareSprite` instead of a regular `SDL_Surface` (now replaced by `render_text`), as well as the `can_render` method which is no longer useful (`render_text` and `render_on` already throw an informative exception on a missing character).
[what-is-ci]: …
> Rewrite and re-document the BitmapFont class

- .github/workflows/run_tests.yml
- doc/modules/ext/ttf.rst
- doc/news.rst
- examples/ttf.py
- sdl2/ext/compat.py
- sdl2/ext/sprite.py
- sdl2/ext/ttf.py
- sdl2/test/sdl2ext_font_test.py
- sdl2/test/sdl2ext_sprite_test.py
This PR adds a new class `FontTTF` that wraps the `SDL_ttf` API, and deprecates the existing `FontManager` class.
The main changes and improvements of the `FontTTF` class over the `FontManager` class include:
- Support for specifying font sizes in pixel height in addition to pt
- Separate FontTTF objects for each font file
- Supports left/right/center justification for multiline text
- Supports custom line heights for multiline text
- More closely matches the usage of the `BitmapFont` class for better API consistency.
As part of the bug-fixing process, this PR also makes the TTF and Sprite tests more stable (by manually running garbage collection after each test) and makes the Sprite tests faster.
[what-is-ci]: https://help.github.com/en/actions/building-and-testing-code-with-continuous-in …
> Add the FontTTF bindings for the TTF API

- sdl2/test/sdlttf_test.py
SDL2_ttf 2.0.18 with Harfbuzz-based font rendering gives a width
slightly narrower than 2.0.15, so tolerate that.
Previously the height was not allowed to be 22 or 23, but if 21 and 25
are both acceptable values, then anything in between also seems fine;
for better future-proofing, accept a range.
Resolves: https://github.com/marcusva/py-sdl2/issues/212
[news-file]: …
> sdlttf_test: Accept width and height within a range

- doc/news.rst
- sdl2/dll.py
- sdl2/test/sdlimage_test.py
- sdl2/test/sdlmixer_test.py
- sdl2/test/sdlttf_test.py
- sdl2/test/version_test.py
Closes #228.
This PR fixes the unit tests that expect the SDL2 minor version to always be 0, and also updates the internal version string-to-int and int-to-string functions to correctly parse the new versions. Note that the updated code assumes that the patch level for future SDL2 releases will always be a single digit, which I think seems safe.
[news-file]: …
> Add proper support for SDL2's new versioning scheme

- sdl2/dll.py
- sdl2/test/sdlimage_test.py
- sdl2/test/sdlmixer_test.py
- sdl2/test/sdlttf_test.py
- sdl2/test/version_test.py
Continuation from #229. Fixes #228 (really this time).
* test: Add more realistic tests of SDL_VERSIONNUM
The minor version overflows into the thousands digit in 2.23.0 and up.
Because the major version is fixed at 2 until SDL 3 (which will be a
separate library, like the difference between SDL 1.2 and 2), the
numbers from here can still be used as a sort order, but are now a bit
more confusing than they used to be.
* test: Avoid assertions that will break in upcoming versions
Future SDL 2 versions are going to make more use of the minor version,
so SDL 2.0.22, SDL_image 2.0.5, SDL_mixer 2.0.4 and SDL_ttf 2.0.18 will
be followed by 2.24.0, 2.6.0, 2.6.0 and 2.20.0 respectively.
This means assertions like version.patch >= 5 will no longer be true, so
compare the entire version number as a …
> Handle SDL 2.23+ new versioning scheme

- sdl2/test/power_test.py
If a Linux laptop has been configured to stop charging the battery at
a value below 100% (to increase battery longevity by preventing
over-charging), and is charged to the configured maximum, SDL reports
that as SDL_POWERSTATE_UNKNOWN but still reports a percentage.
---
I wouldn't have noticed this, except that my laptop happens to make the assertion fail most of the time :-)
[news-file]: …
> power_test: Relax assertions about known information

- doc/news.rst
- sdl2/test/pixels_test.py
- sdl2/test/sdl2ext_array_test.py
- sdl2/test/sdl2ext_draw_test.py
- sdl2/test/sdl2ext_image_test.py
- sdl2/test/sdl2ext_pixelaccess_test.py
- sdl2/test/sdl2ext_surface_test.py
Closes #227. Tested and working on a Power Mac G5 with SDL2 2.0.22 and Void Linux PowerPC 64-bit, except for the renderer tests which segfault because of a GL/Mesa/nouveau configuration issue (`glxgears` segfaults immediately too, so not a SDL2/PySDL2 problem).
So far all the fixes have been to the unit tests themselves, which were typically failing because they weren't written properly with big-endian in mind. The only area I have hesitations about are the `pixels3d` and related Numpy access functions, since the orders of RGBA tuples are inverted from little-endian systems, meaning that any code making assumptions about the byte order in those arrays wouldn't be readily portable. Not sure if that's something that should be left to developers themselves or taken care of internally in …
> Fix unit tests on big-endian systems

- sdl2/test/timer_test.py
- sdl2/timer.py
SDL_TICKS_PASSED is meant to compare 32-bit tick counts in a way that works correctly when the counter has recently wrapped around. The Python implementation just did a straight integer comparison. Fix it and add a regression test.
[news-file]: https://github.com/marcusva/py-sdl2/blob/master/doc/news.rst
> Fix SDL_TICKS_PASSED (#234)

- sdl2/test/sdlmixer_test.py
All the decoders I've tried think sdl2/test/resources/soundtest.mp3
is approximately 0.15 seconds long.
Resolves: https://github.com/py-sdl/py-sdl2/issues/243
---
This fixes a test failure with SDL_mixer 2.6.1 compiled to use libmpg123 for MP3. Debian's versions of `extract(1)` and Audacity agree that the test file is about 0.15 seconds long.
[news-file]: …
> sdlmixer_test: Accept a lower value for sample MP3 duration

- doc/modules/ext/mouse.rst
- doc/modules/sdl2ext.rst
- doc/news.rst
- examples/particles.py
- sdl2/ext/__init__.py
- sdl2/ext/mouse.py
- sdl2/ext/window.py
- sdl2/test/sdl2ext_mouse_test.py
Closes #10. This PR adds a new `sdl2.ext` module that provides friendly Pythonic wrappers around SDL2's mouse functions, making possible to work with the mouse without using `ctypes` and generally allowing the writing of simpler and more readable code.
> Add sdl2.ext.mouse module

- sdl2/test/version_test.py
The default format is going to change in 2.25.x, and in git main it currently starts with "SDL-".
SDL specifically documents the result of this function as "not intended to be reliable in any way", so it seems wrong to have pysdl2's tests fail whenever the format changes. To address that, turn unexpected formats into an xfail, so that they're flagged as something to investigate but do not make the unit tests fail when used as a QA gate.
Closes: https://github.com/py-sdl/py-sdl2/issues/248
[auto-close-documentation]: https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keywo …
> version_test: Don't assert that SDL_GetRevision() starts with http

- sdl2/test/audio_test.py
- sdl2/test/conftest.py
- sdl2/test/gamecontroller_test.py
- sdl2/test/hints_test.py
- sdl2/test/joystick_test.py
- sdl2/test/sdl_test.py
- sdl2/test/sdlmixer_test.py
- sdl2/test/sensor_test.py
- sdl2/test/touch_test.py
- sdl2/test/video_test.py
SDL_GetError works like Standard C errno: if a call fails it will (generally) set the error indicator, but if a call succeeds there is no guarantee about whether the error indicator has been set, cleared, or left at its previous value.
The SDL documentation says this:
The message is only applicable when an SDL function has signaled an
error. You must check the return values of SDL function calls to
determine when to appropriately call SDL_GetError(). You should not
use the results of SDL_GetError() to decide if an error has occurred!
Sometimes SDL will set an error string even when reporting success.
In particular, with a SDL 2.27.x git snapshot, a successful SDL_Init can leave the error indicator set to a message about inability to open an input device node, and this does not mean it has …
> tests: Don't assume SDL_Init will leave SDL_GetError unset

- sdl2/ext/image.py
- sdl2/test/sdl2ext_image_test.py
* tests: Test image loading in a predictable order
This makes it easier to compare different architectures' ability to load
the various file formats.
* ext.image: Make comments and variable naming less confusing
Somewhat confusingly, SDL uses ABGR8888 to represent a format where each
32-bit unit can be interpreted as 0xAABBGGRR in native endianness,
whereas it uses ARGB32 to represent a format where 8-bit units can be
interpreted as AA, RR, GG, BB in that order. Stick to the same
terminology as SDL here, and be clearer about what we mean.
No functional change intended.
* tests: Skip pixel comparison when loading XCF files on big-endian
This isn't working for me. On x86 I get the desired rendering, but on
s390x, for example the pixels in the first row that should have been
green and red …
> Skip test for big-endian .xcf loading

- doc/modules/ext/displays.rst
- doc/modules/ext/input.rst
- doc/modules/sdl2ext.rst
- doc/news.rst
- examples/draw.py
- examples/ttf.py
- sdl2/ext/__init__.py
- sdl2/ext/common.py
- sdl2/ext/input.py
- sdl2/test/sdl2ext_input_test.py
- sdl2/test/sdl2ext_test.py
This PR adds a new `sdl2.ext` module with a series of functions that allow Pythonic handling of SDL input events without needing to deal directly with `SDL_Event` loops, as well as an additional function in `sdl2.ext.common` for specifically handling quit requests. The current PR contains functions for handling keypress, mouse click, and text input events, but joystick/controller events will hopefully be added in a future update.
In general, these new functions should make it faster and easier for SDL2 beginners (and veterans) to write clean, readable input processing loops while also allowing a great deal of flexibility.
[auto-close-documentation]: …
> Add new sdl2.ext module for handling SDL input events

- doc/conf.py
From: Chris Lamb
The goal of reproducible builds is that a rebuild of the same source code with the same compiler, libraries, etc. should result in the same binaries. SOURCE_DATE_EPOCH provides a standard way for build systems to fill in the date of the latest source change, typically from a git commit or from metadata like the debian/changelog in Debian packages.
This does not change anything if SOURCE_DATE_EPOCH is not defined; the intention is that a larger build system like a Debian package will define it.
Please see https://reproducible-builds.org/ for more information about reproducible builds.
Bug-Debian: https://bugs.debian.org/1031412 …
> Make the build reproducible

- .github/workflows/run_tests.yml
- sdl2/ext/mouse.py
- sdl2/test/audio_test.py
- sdl2/test/clipboard_test.py
- sdl2/test/conftest.py
- sdl2/test/filesystem_test.py
- sdl2/test/gamecontroller_test.py
- sdl2/test/hidapi_test.py
- sdl2/test/hints_test.py
- sdl2/test/joystick_test.py
- sdl2/test/render_test.py
- sdl2/test/sdl2ext_mouse_test.py
- sdl2/test/sdl_test.py
- sdl2/test/sdlmixer_test.py
- sdl2/test/sensor_test.py
- sdl2/test/shape_test.py
- sdl2/test/syswm_test.py
- sdl2/test/touch_test.py
- sdl2/test/video_test.py
Closes #257. This PR fixes a bunch of unsafe assumptions about SDL errors in the existing test suite, and also fixes/skips a number of tests that don't currently work right with Wayland or XWayland.
This also tries re-adding Python 2.7 runners to the CI, since official support got removed from `setup-python` this week.
> Improve unit tests and restore Python 2.7 CI runners

- AUTHORS.txt
- sdl2/test/gamecontroller_test.py
In Ubuntu, we're seeing test failures of the following pattern when moving from libsdl2 2.28.1+dfsg-1 to 2.28.2+dfsg-1:
> assert sdl2.SDL_GetError() == b""
E AssertionError: assert b'Unexpected ...r element crc' == b''
E   Full diff:
E   - b''
E   + b'Unexpected controller element crc'
This looks like an issue similar to that fixed in commit 8c39f40. We should check the relevant return value, and only if it indicates failure should we attach any particular meaning to the return value of SDL_GetError().
I'm not sure if this is entirely correct and would appreciate review and feedback! In particular it's not clear to me if this 'Unexpected controller element crc' should result in a test failure and needs fixing elsewhere, and/or if it was caused by a change other than a version bump of …
> tests: SDL_GetError() != b'' isn't an error

- sdl2/test/hidapi_test.py
On my Linux system, enumeration succeeds, but the error indicator gets set as a side-effect (which appears to be because the loader checks whether the symbol exists in SDL or a direct dependency before it dlopens libudev).
The API of SDL_hid_enumerate does not make it possible to distinguish between successfully returning an empty list of devices (returns NULL with the error indicator in an undefined state) and a failure (returns NULL with the error indicator set), and systems that run automated tests usually don't have any HID game controllers connected, so we can't make any meaningful use of the error indicator here.
Helps: https://github.com/py-sdl/py-sdl2/issues/257
[what-is-ci]: https://help.github.com/en/actions/building-and-testing-code-with-continuous-integration/about-continuous-i …
> test: Don't assert that SDL_hid_enumerate doesn't set error

- sdl2/test/video_test.py
This brings py-sdl2 a bit closer to fully resolving #257, by reducing the number of places where it assumes `SDL_GetError != ''` implies that there was an error. #267, #269, etc. are targeted versions of this addressing places where a newer SDL2 release *does* break that assumption, whereas this PR is a preventative version addressing places where a newer SDL2 release *might* break that assumption but has not done so yet.
This PR only covers `video_test`, treating all other tests as out-of-scope. Many other test modules will eventually need a change similar to this one.
* video_test: Don't check error unless a function failed
Helps: https://github.com/py-sdl/py-sdl2/issues/257
* video_test: Use _check_error_msg() a bit more often
* video_test: Mitigate unsuitability of SDL_GetError() for …
> Partially resolve #257: video_test

- sdl2/test/clipboard_test.py
- sdl2/test/joystick_test.py
- sdl2/test/keyboard_test.py
- sdl2/test/pixels_test.py
- sdl2/test/render_test.py
- sdl2/test/rwops_test.py
- sdl2/test/sdl2ext_draw_test.py
- sdl2/test/sdl2ext_font_test.py
- sdl2/test/sdl2ext_spritesystem_test.py
- sdl2/test/sdl_test.py
- sdl2/test/sdlgfx_test.py
- sdl2/test/sdlimage_test.py
- sdl2/test/surface_test.py
- sdl2/test/syswm_test.py
- sdl2/test/video_test.py
Closes #257 (for real this time, I think). This fixes a bunch of assorted unit tests to only check for `SDL_GetError` output when a function's return value indicates a failure, since `SDL_SetError` is often used internally by SDL2 to set non-fatal warning messages (leading to tests breaking unexpectedly with new SDL releases).
> Remove more misuse of SDL_GetError in tests

- sdl2/test/hints_test.py
Setting a SDL hint with an empty name does not make sense.
This is also what upstream thinks:
https://github.com/libsdl-org/SDL/pull/12538#issuecomment-2725851422
Remove test case testing setting a hint with no name.
> Remove test setting hint with empty string

- sdl2/test/sdl2ext_test.py
The test meant to call `SDL_FlushEvents()` to flush all events, but instead only flushed `SDL_FIRSTEVENT`. This mistake was harmless until SDL3, which does have queued events at this point that must be flushed for the test expectations to be met.
> Fix test_get_events failure with sdl2-compat

- sdl2/test/video_test.py
`SDL_SetWindowBrightness` and `SDL_SetWindowGammaRamp` are not available anymore in SDL3,
so fail when used in sdl2-compat.
> Set window gamma ramp and set window brightness can fail

- sdl2/test/video_test.py
Wayland does not support changing the icon or position of  a window, so mark those tests as expected failures.
> Detect wayland video driver, and mark 2 tests as expected failures on wayland
